version: "3.8"
services: 
  backend:
    build: ./backend
    container_name: MERN_backend_c
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - redis
  frontend:
    build: ./frontend
    container_name: MERN_frontend_c
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
  redis:
    image: "redis:latest"